### ISSUE TITLE
We need to be able to support joining on metadata based on partial code matches (e.g., no `valueuom`).

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_extract#10]
https://github.com/mmcdermott/MEDS_transforms/blob/b5f027764441a383e9510804c37633e1b0f30e0f/MIMIC-IV_Example/configs/event_configs.yaml#L211

**Comment by mmcdermott** [comment]
Closed by #62 (feature) + #63 (followup validation fixes). 

`extract_code_metadata` now supports partial metadata matching via a `_match_on` key inside the `_metadata` block. For composite codes like `f"{\$medication_name}//{\$dose}"`, you declare which code component(s) the metadata table should match on:

```yaml
medications:
  med:
    code: 'f"{\$medication_name}//{\$dose}"'
    time: '\$prescribed_at::"%Y-%m-%d"'
    _metadata:
      medication_classes:
        _match_on: medication_name   # ← partial match on just this component
        drug_class: drug_class
```

The metadata join happens against the per-row `code_components` struct (see #59), so the match works regardless of what other components the full code carries. [README](https://github.com/mmcdermott/MEDS_extract/blob/dev/README.md#metadata-linking) has a worked example using `medication_classes.csv` from the built-in example dataset.
